#!/bin/bash

# This script starts up a local EEMT instance, and uses SSH to
# submit workers on the OSG system.

set -e

# settings
LOCAL_WORK_DIR=`pwd`
LOCAL_EEMT_INSTALL=/home/eemt/git/eemt
export TCP_LOW_PORT=20000
export TCP_HIGH_PORT=60000 

# safty check
if [ -e run-workflow ]; then
    echo "Do not run from the eemt checkout!"
    exit 1
fi

# arguments
DEM=$1
DAYS=$2

cd $LOCAL_EEMT_INSTALL

# run the workflow
# for start-year the DAYMET average is year 0000, the time series data are from 1980 to 2012,
# to start and end in a single year use the same year
./run-workflow \
  --name EEMT_OPAL2 \
  --start-year 0000 \
  --end-year 0000 \
  -O $LOCAL_WORK_DIR \
   $LOCAL_WORK_DIR/$DEM

echo
echo "Output files in $LOCAL_WORK_DIR"
echo

